app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(`first_link-gender_item-submit` = "click")
app$setInputs(`second_link-seconnd_simple-submit` = "click")
app$snapshot()
app$setInputs(`first_link-gender_item-gender_item` = "F")
app$setInputs(`first_link-gender_item-submit` = "click")
app$snapshot()
app$setInputs(`first_link-first_simple-other_langs` = "4")
app$setInputs(`first_link-first_simple-other_langs` = c("4", "6"))
app$setInputs(`first_link-first_simple-years_of_experience` = 1)
app$setInputs(`first_link-first_simple-years_of_experience` = 2)
app$setInputs(`first_link-first_simple-questio_need` = "Yes")
app$setInputs(`first_link-first_simple-submit` = "click")
app$snapshot()
app$setInputs(update_values = "click")
app$snapshot()
app$setInputs(`second_link-seconnd_simple-questio_need` = "No")
app$setInputs(`second_link-seconnd_simple-submit` = "click")
app$setInputs(`second_link-with_default-test3` = "3")
app$setInputs(`second_link-with_default-test2` = "2")
app$setInputs(`second_link-with_default-test4` = "Second choice")
app$setInputs(`second_link-with_default-test4` = c("Second choice", "First choice"))
app$setInputs(`second_link-with_default-submit` = "click")
app$snapshot()
app$setInputs(`second_link-with_default-test1` = "hehe")
app$setInputs(`second_link-with_default-test6` = 1)
app$setInputs(`second_link-with_default-test6` = 4)
app$setInputs(`second_link-with_default-test5` = "2")
app$setInputs(`second_link-with_default-submit` = "click")
app$snapshot()
app$setInputs(`second_link-gender_react-test2` = "Goob")
app$setInputs(`second_link-gender_react-test3` = "5")
app$setInputs(`second_link-gender_react-test3` = c("5", "2"))
app$setInputs(`second_link-gender_react-test3` = c("5", "2", "7"))
app$setInputs(`second_link-gender_react-test1` = "hehe")
app$setInputs(`second_link-gender_react-submit` = "click")
app$snapshot()
