app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(`first_link-gender_item-gender_item` = "F")
app$setInputs(`first_link-gender_item-submit` = "click")
app$snapshot()
app$setInputs(`first_link-first_simple-shiny_positive_text` = "everything")
app$setInputs(`first_link-first_simple-other_langs` = "3")
app$setInputs(`first_link-first_simple-other_langs` = c("3", "5"))
app$setInputs(`first_link-first_simple-other_langs` = c("3", "5", "16"))
app$setInputs(`first_link-first_simple-years_of_experience` = -1)
app$setInputs(`first_link-first_simple-questio_need` = "Yes")
app$setInputs(`first_link-first_simple-submit` = "click")
app$snapshot()
app$setInputs(`first_link-first_simple-years_of_experience` = 0)
app$setInputs(`first_link-first_simple-years_of_experience` = 1)
app$setInputs(`first_link-first_simple-submit` = "click")
app$setInputs(get_df_first = "click")
app$setInputs(update_values = "click")
app$snapshot()
app$setInputs(`second_link-seconnd_simple-submit` = "click")
app$setInputs(`second_link-with_default-test2` = "2")
app$setInputs(`second_link-with_default-test1` = "whatever")
app$setInputs(`second_link-with_default-test3` = "2")
app$setInputs(`second_link-with_default-test5` = "3")
app$setInputs(`second_link-with_default-test4` = "First choice")
app$setInputs(`second_link-with_default-test4` = c("First choice", "Third choice"))
app$setInputs(`second_link-with_default-submit` = "click")
app$snapshot()
app$setInputs(`second_link-from_gsheet-test1` = "Like")
app$setInputs(`second_link-from_gsheet-test1` = "Like this")
app$setInputs(`second_link-from_gsheet-test2` = 5)
app$setInputs(`second_link-from_gsheet-test3` = "Something")
app$setInputs(`second_link-from_gsheet-test4` = "2")
app$setInputs(`second_link-from_gsheet-test4` = c("2", "1"))
app$setInputs(`second_link-from_gsheet-test4` = c("2", "1", "3"))
app$setInputs(`second_link-from_gsheet-test5` = "More")
app$setInputs(`second_link-from_gsheet-test6` = "2")
app$snapshot()
app$setInputs(`second_link-from_gsheet-submit` = "click")
app$setInputs(`second_link-gender_react-submit` = "click")
app$waitFor("($('#shiny-modal').data('bs.modal') || {}).isShown", 1000)
app$snapshot()
app$executeScript("$('.modal').modal('hide');")
app$setInputs(`second_link-gender_react-test1` = "good")
app$setInputs(`second_link-gender_react-test2` = "Bad")
app$setInputs(`second_link-gender_react-test3` = "1")
app$setInputs(`second_link-gender_react-test3` = c("1", "2"))
app$setInputs(`second_link-gender_react-test3` = c("1", "2", "3"))
app$setInputs(`second_link-gender_react-submit` = "click")
app$setInputs(get_df_second = "click")
app$snapshot()
