app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$snapshot()
app$setInputs(`first_link-gender_item-gender_item` = "F")
app$setInputs(`first_link-gender_item-submit` = "click")
app$setInputs(`first_link-first_simple-shiny_positive_text` = "Easy of use")
app$setInputs(`first_link-first_simple-other_langs` = "5")
app$setInputs(`first_link-first_simple-other_langs` = c("5", "16"))
app$setInputs(`first_link-first_simple-years_of_experience` = 3)
app$setInputs(`first_link-first_simple-questio_need` = "Yes")
app$setInputs(`first_link-first_simple-submit` = "click")
app$setInputs(get_df_first = "click")
app$setInputs(update_values = "click")
app$snapshot()
app$setInputs(`second_link-seconnd_simple-questio_need` = "Maybe")
app$setInputs(`second_link-seconnd_simple-submit` = "click")
app$snapshot()
app$setInputs(`second_link-with_default-submit` = "click")
app$setInputs(`second_link-with_default-test2` = "1")
app$snapshot()
app$setInputs(`second_link-with_default-test1` = "mandator")
app$setInputs(`second_link-with_default-test1` = "mandatory")
app$setInputs(`second_link-with_default-test6` = 3)
app$setInputs(`second_link-with_default-test3` = "2")
app$setInputs(`second_link-with_default-test5` = "3")
app$setInputs(`second_link-with_default-test4` = "First choice")
app$setInputs(`second_link-with_default-test4` = c("First choice", "Third choice"))
app$setInputs(`second_link-with_default-submit` = "click")
app$setInputs(`second_link-gender_react-submit` = "click")
app$snapshot()
app$setInputs(`second_link-gender_react-test1` = "good thinking")
app$setInputs(`second_link-gender_react-test2` = "Goob")
app$setInputs(`second_link-gender_react-test3` = "6")
app$setInputs(`second_link-gender_react-test3` = c("6", "7"))
app$setInputs(`second_link-gender_react-test3` = c("6", "7", "5"))
app$setInputs(`second_link-gender_react-submit` = "click")
app$setInputs(get_df_second = "click")
app$snapshot()
